# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: PepePotter
# Description of the Site
description: "Expecto patronum - focus your positive energy with Pepe Potter coin"
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: PepePotter, Crypto, Coin
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://img.ecartelera.com/noticias/72100/72171-h3.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: pepepottercoin@gmail.com
facebook_username: 
twitter_username: pepepottercoin
instagram_username: 
linkedin_username: 
github_username:  pepepotter
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: PEPOT
# URL for the Image of the Author
author-image: [url=https://ibb.co/zn4CbM1][img]https://i.ibb.co/zn4CbM1/b2840837-f655-49ce-bccd-3dc103818f36.png[/img][/url]
# 60 Words About the Author
author-about: Pepe Potter(PEPOT) is a magical token that brings the enchanting world of Harry Potter to the blockchain. As a community-driven token, Pepe Potter aims to unite fans of the beloved wizarding series, providing them with a unique opportunity to embark on a thrilling journey in the decentralized realm.
author-url: https://github.com/pepepotter

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
